kind: Deployment
apiVersion: app/v1
metadata:
        name: abctechnologies-dep
        space:
                replicas: 2
                miniReadySeconds: 45
                strategy:
                        type: RollingUpdate
                        rollingUpdate:
                                maxUnavailable: 1
                                maxSurge: 2
        selector:
                matchLabels:
                        app: abc-tech-projapp
        template:
                metadata:
                        labels:
                                app: abc-tech-projapp
        spec:
                containers:
                        - image: reddymnk/mydevops
                          names: abc-tech-projapp
---
kind: Service
apiVersion: v1
metadata:
        name: abc-tech-service
spec:
        type: NodePort
        selector:
                app: abc-tech-projapp
        ports:
                - port: 80
                  targetPort: 8080
