---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydevopsabc-app
  specs:
    replicas: 2
    miniReadySeconds: 45
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 2
  selector:
    matchLabels:
      app: mydevopsabc
  template:
    metadata:
      labels:
        app: mydevopsabc
  specs:
    containers:
      - image: mydevopsabc
        names: mydevopsabc

---
kind: Service
apiVersion: v1
metadata:
  name: mydevopsabc
specs:
  type: NodePort
  selector:
    app: mydevopsabc
  ports:
    - port: 80
      targetPort: 8080

