apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydevopsabc-app
  labels:
    app: mydevopsabc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydevopsabc
  template:
    metadata:
      labels:
        app: mydevopsabc
    spec:
      containers:
      - name: mydevopsabc
        image: reddymnk/mydevopsabc:latest
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: abc-tech-service
spec:
  selector:
    app: mydevopsabc
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 192.168.1.11
