apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydevopsabc-app
  labels:
    app: mydevopsabc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydevopsabc
  template:
    metadata:
      labels:
        app: mydevopsabc
    spec:
      containers:
      - name: mydevopsabc
        image: reddymnk/mydevopsabc:latest
        ports:
        - protocol: TCP
          port: 8089
          TargetPort: 8080
       type: ClusterIP
