apiVersion: v1
kind: Service
metadata:
  name: kubernetes
spec:
  selector:
    app: kubernetes
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 443
  type: LoadBalancer
  ClusterIP:
    - 10.85.0.15
  externalIPs:
    - 10.168.1.15
